issues:
  include:
    # comment on exported (.+) should be of the form "(.+)..."
    - EXC0014
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: cmd/
      linters:
        # Used for cmd setup
        - gochecknoinits
linters:
  enable-all: true
  disable:
    # Cyclomatic dependency checking is unnecessary here
    - cyclop
    # We don't want to specify every valid dependency
    - depguard
    # False positive issues
    - exhaustive
    # Overly verbose code
    - exhaustruct
    # Allow print messages
    - forbidigo
    # Nitpick
    - funlen
    # We don't use ginkgo
    - ginkgolinter
    # We want to use globals
    - gochecknoglobals
    # We don't need to worry about cognitive complexity here
    - gocognit
    # Nitpick
    - godot
    # We use TODO comments
    - godox
    # Using gofumpt instead
    - gofmt
    # Too noisy for this project
    - ireturn
    # Long lines are fine
    - lll
    # Too much false-positive potential
    - misspell
    # False positive issues
    - musttag
    # Leave formatting up to gofumpt
    - nlreturn
    # False positives when using necessary snake case
    - tagliatelle
    # Deprecated
    - tenv
    # Nitpick
    - varnamelen
    # Let gofumpt do the formatting
    - whitespace
    # Let gofumpt do the formatting
    - wsl
    # Temporary
    - wrapcheck
    - err113
linters-settings:
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    # Ignore file mode numbers as they are commonly known
    ignored-numbers:
      - "0o600"
      - "0o666"
      - "0o755"
  loggercheck:
    # The sloglint linter already handles this
    slog: false

  perfsprint:
    integer-format: true
    int-conversion: true
    error-format: true
    err-error: false
    errorf: true
    string-format: true
    sprintf1: true
    # Using format string is more flexible to changes
    strconcat: false
    bool-format: true
    hex-format: true
