[package]
name = "evergreen-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde = { version = "1.0.219", features = ["std", "serde_derive"] }
serde_json = "1.0.140"
