run:
	@cargo run

build:
	@cargo build --target aarch64-apple-darwin

test:
	@cargo test

lint:
	@cargo clippy

format:
	@cargo fmt

clean:
	@cargo clean

setup:
	@cargo install

.PHONY: run build test lint format clean setup
